name: Hello World

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secret.VERCEL_PROJECT_ID }}
  VERCEL_DEPLOY_TOKEN: ${{ secret.VERCEL_DEPLOY_TOKEN }}

on:
  push:


jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      
      - name: Show node version
        run: echo hello world 

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with: 
          version: 8
          run_install: false
        
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build the app
        run: npm run build

  snapshot: 
    runs-on: ubuntu-latest

    steps:
      - name: Build snapshot
        run: node snapshot.js
      
      - name: Move snapshot
        run: mv -v /gen/* /static/
  
  # deploy:
  #   runs-on: ubuntu-latest

  #   steps: 